OD-590 [Feature] Added transtation to Widget-ChartPie
Fliplet/fliplet-widget-chart-pie pull request #37
Opened 2021-10-04 09:09 UTC by OleksandrLavrynenko

@sofiiakvasnevska @inna-bieshulia

OD-590 https://weboo.atlassian.net/browse/OD-590

## Description
Added user translations to widget - ChartPie

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2021-10-11 16:20 UTC, tonytlwu requested changes

2021-10-11 16:20 UTC, tonytlwu commented on js/build.js
> +                // Summarise data
```suggestion
                // Summarize data
```

2021-10-11 16:20 UTC, tonytlwu commented on js/build.js
> +      var themeInstance = {
Why is this here?

2021-10-11 18:16 UTC, OleksandrLavrynenko commented on js/build.js
> +      var themeInstance = {
Sorry. This code was used for the test

2021-10-13 12:45 UTC, tonytlwu reviewed
@romanyosyfiv @inna-bieshulia Translation looks ready. This can be tested once API is ready.

2022-05-04 17:57 UTC, closed without merging